// Code generated by Kitex v0.6.1. DO NOT EDIT.

package reverseservice

import (
	server "github.com/cloudwego/kitex/server"
	reverse "github.com/kaleidoyao/API-GateWay/rpc_server_reverse/kitex_gen/reverse"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler reverse.ReverseService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
