// Code generated by Kitex v0.6.1. DO NOT EDIT.

package reverseservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	reverse "github.com/kaleidoyao/API-GateWay/rpc_server_reverse/kitex_gen/reverse"
)

func serviceInfo() *kitex.ServiceInfo {
	return reverseServiceServiceInfo
}

var reverseServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ReverseService"
	handlerType := (*reverse.ReverseService)(nil)
	methods := map[string]kitex.MethodInfo{
		"reverseMethod": kitex.NewMethodInfo(reverseMethodHandler, newReverseServiceReverseMethodArgs, newReverseServiceReverseMethodResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "reverse",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.6.1",
		Extra:           extra,
	}
	return svcInfo
}

func reverseMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*reverse.ReverseServiceReverseMethodArgs)
	realResult := result.(*reverse.ReverseServiceReverseMethodResult)
	success, err := handler.(reverse.ReverseService).ReverseMethod(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newReverseServiceReverseMethodArgs() interface{} {
	return reverse.NewReverseServiceReverseMethodArgs()
}

func newReverseServiceReverseMethodResult() interface{} {
	return reverse.NewReverseServiceReverseMethodResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ReverseMethod(ctx context.Context, request *reverse.ReverseRequest) (r *reverse.ReverseResponse, err error) {
	var _args reverse.ReverseServiceReverseMethodArgs
	_args.Request = request
	var _result reverse.ReverseServiceReverseMethodResult
	if err = p.c.Call(ctx, "reverseMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
