// Code generated by hertz generator.

package gateway

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _calculatemethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _greetingmethodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reversemethodMw() []app.HandlerFunc {
	// your code...
	return nil
}
